### ISSUE TITLE
Update my résumé

### ISSUE THREAD

**Issue by jessica-hartwell** [executive-consultants-of-los-angeles/rsum#81]
Add a working cv for the site.

- [ ] Introduction
- [ ] Summary
- [ ] Skills
- [ ] Experience
- [ ] Education
- [ ] Contact

**Comment by eclacfo** [comment]
One day you'll finish this. 

I hope you like kittens.
The rescue, look how tiny![kitty rescue](https://img.buzzfeed.com/buzzfeed-static/static/2015-06/10/16/campaign_images/webdr15/this-brave-kitten-and-his-tiny-cast-will-melt-you-2-5954-1433967674-1_dblbig.jpg)

**Comment by eclacfo** [comment]
![cutestbirdies](https://user-images.githubusercontent.com/30249148/31107789-d0d6bca2-a7a9-11e7-8aaf-8db82285582a.jpg)
